default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: sample_app_docker_development

test:
  <<: *default
  database: sample_app_docker_test

production:
  <<: *default
  database: sample_app_docker
